"""phase2_vendor_quotation

Revision ID: 972b65bd67fa
Revises: 086f2345f317
Create Date: 2026-07-29 23:51:13.957332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972b65bd67fa'
down_revision: Union[str, Sequence[str], None] = '086f2345f317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=512), nullable=False),
    sa.Column('contact_person', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('tax_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_company_name'), 'vendors', ['company_name'], unique=False)
    op.create_index(op.f('ix_vendors_is_deleted'), 'vendors', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_vendors_workspace_id'), 'vendors', ['workspace_id'], unique=False)
    op.create_table('quotations',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('quotation_number', sa.String(length=128), nullable=False),
    sa.Column('quotation_date', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADED', 'PROCESSING', 'PROCESSED', 'FAILED', 'REJECTED', name='quotationstatus'), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['procurement_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotations_is_deleted'), 'quotations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_quotations_project_id'), 'quotations', ['project_id'], unique=False)
    op.create_index(op.f('ix_quotations_quotation_number'), 'quotations', ['quotation_number'], unique=False)
    op.create_index(op.f('ix_quotations_status'), 'quotations', ['status'], unique=False)
    op.create_index(op.f('ix_quotations_vendor_id'), 'quotations', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotations_vendor_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_status'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_quotation_number'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_project_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_is_deleted'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_index(op.f('ix_vendors_workspace_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_is_deleted'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_company_name'), table_name='vendors')
    op.drop_table('vendors')
    # ### end Alembic commands ###
